server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: true
  application:
    name: listaTarefaApplication
  profiles:
    active:
    - test
    
auth:
  jwt:
    token:
      secret: ${JWT_TOKEN_SECRET}
      expiration: 2
    refresh-token:
      expiration: 8 
          
